import type { DiscSlug, VenueSlug } from './content';

/* =========================================================
   ARTICLES - Bilgi Merkezi
   ========================================================= */
export type Article = {
  slug: string;
  title: string;
  summary: string;
  excerpt: string;
  publishedAt: string;
  readMin: number;
  category: 'Akustik' | 'Ses Sistemi' | 'LED' | 'Stüdyo' | 'Mevzuat';
  related: { discipline?: DiscSlug; venue?: VenueSlug };
  body: Array<
    | { type: 'p'; text: string }
    | { type: 'h2'; text: string }
    | { type: 'h3'; text: string }
    | { type: 'ul'; items: string[] }
    | { type: 'callout'; title: string; text: string }
    | { type: 'table'; caption?: string; headers: string[]; rows: string[][] }
  >;
};

export const ARTICLES: Article[] = [
  {
    slug: 'rt60-nedir',
    title: 'RT60 nedir, nasıl ölçülür ve neden kritik?',
    summary: 'Akustik mühendislikte temel metrik olan RT60\'ı tanımlar, ölçüm yöntemini ve mekân tipine göre hedef değerleri açıklar.',
    excerpt: 'Bir mekânın "akustik karakterini" tek bir sayıya indirgemek mümkün değil - ama RT60, en yakın olanı.',
    publishedAt: '2026-04-12',
    readMin: 6,
    category: 'Akustik',
    related: { discipline: 'akustik' },
    body: [
      { type: 'p', text: 'RT60 (Reverberation Time 60), bir ses kaynağının kapatılmasının ardından mekândaki ses basınç seviyesinin 60 dB düşmesi için geçen süredir. Birim olarak saniye (s) cinsinden ifade edilir ve bir mekânın akustik karakterini özetleyen en yaygın metriktir.' },
      { type: 'h2', text: 'Neden 60 dB?' },
      { type: 'p', text: '60 dB, insan kulağının "duyulabilir" eşiğin ortalama 1 milyonda biri kadar zayıf bir basınç farkına denk gelir. Pratikte ölçüm sırasında 60 dB\'lik düşüşü doğrudan kaydetmek zordur (arka plan gürültüsü engel olur), bu yüzden T20 (20 dB düşüş × 3) veya T30 (30 dB düşüş × 2) kullanılır.' },
      { type: 'h2', text: 'Mekân tipine göre hedef değerler' },
      { type: 'table', caption: 'Mekân tipine göre tipik RT60 hedefleri (orta band, 500 Hz – 2 kHz)', headers: ['Mekân', 'RT60 Hedef', 'Not'], rows: [
        ['Stüdyo kontrol odası', '0.25 – 0.32 s', 'RFZ + bass trap zorunlu'],
        ['Restoran', '0.6 – 0.9 s', 'Konuşma netliği ön planda'],
        ['Otel ballroom', '1.1 – 1.4 s', 'Çok amaçlı, değişken akustik'],
        ['Konferans salonu', '0.5 – 0.7 s', 'STI ≥ 0.62 hedefi ile birlikte'],
        ['Konser sahnesi', '1.2 – 1.6 s', 'Müzik karakteri için yeterli rezonans'],
      ] },
      { type: 'h2', text: 'Ölçüm yöntemi' },
      { type: 'p', text: 'ISO 3382 metodolojisine uygun ölçüm için en az 6 mikrofon noktası ve 2 kaynak konumu gerekir. Kullandığımız tipik ekipman:' },
      { type: 'ul', items: [
        'Sınıf 1 mikrofon: B&K 4189 (ölçüm) + 4192 (yedek)',
        'Yazılım: SMAART v9 ya da ARTA - log-sweep ve MLS kayıt',
        'Hoparlör: omnidirectional (DodecaSound) saha referans kaynağı',
        'Kalibrasyon: 94 dB SPL @ 1 kHz pistonphone ile her ölçüm öncesi',
      ] },
      { type: 'callout', title: 'Yaygın hata', text: 'RT60\'ı tek bir noktada ölçüp tüm mekâna genellemek. Modal davranış oda boyunca değişir - kontrol odası gibi küçük mekânlarda her dinleyici pozisyonu için ayrı ölçüm gerekir.' },
      { type: 'h2', text: 'RT60 hedefe değil ölçüme bakar' },
      { type: 'p', text: 'Bir mekân için "1.0 s ideal" demek yanlıştır. İdeali kullanım amacı belirler. Restoran için 1.0 s konuşma anlaşılırlığını bozar; sinema için 1.0 s diyalog netliğini ortadan kaldırır; ama konser salonu için 1.0 s müziğin "ölü" hissetmesine yol açar.' },
      { type: 'p', text: 'Doğru yaklaşım: hedef RT60\'ı kullanım profiline göre belirle, mevcut durumu ölç, fark hesabını panel + diffüzör mimarisiyle kapat.' },
    ],
  },
  {
    slug: 'restoran-ses-sistemi-rehberi',
    title: 'Restoran ses sistemi tasarımı: 4 zonlu PA ve akustik denge',
    summary: 'Restoran ve barlarda misafir konuşma netliği, arka plan müzik enerjisi ve canlı performans dengesi nasıl kurulur - saha deneyiminden çıkarılmış checklist.',
    excerpt: 'Restoranlarda iyi ses sistemi konuşmayı kapatmaz, müziği bağırtmaz; ortamı taşır.',
    publishedAt: '2026-04-25',
    readMin: 7,
    category: 'Ses Sistemi',
    related: { discipline: 'ses', venue: 'restoran' },
    body: [
      { type: 'p', text: 'Restoran ses sistemi tasarımı, müziğin kötü olmasından çok masada konuşmanın bozulmasıyla başarısız olur. RT60 yüksekse, hangi marka hoparlör kullanırsanız kullanın, müşteriler 1 saat sonra yorgun ayrılır.' },
      { type: 'h2', text: '1. Akustik temel önce' },
      { type: 'p', text: 'Tavan kasetleri, duvar yüzeyleri ve döşeme malzemesi seçimi sistem mimarisinden önce gelir. Cam, beton ve sert ahşap yansıtıcıdır; kumaş, halı ve perforated tavan absorbtir. Tipik hedef: RT60 0.6 – 0.9 s, STI ≥ 0.62.' },
      { type: 'h2', text: '2. Zon mimarisi' },
      { type: 'p', text: 'Tek zonlu sistem restoranların başı belasıdır. Önerilen minimum yapı:' },
      { type: 'table', caption: '180 kişilik restoran için tipik zon yapısı', headers: ['Zon', 'Hoparlör', 'Hedef SPL', 'Kaynak'], rows: [
        ['Z1: Giriş + bekleme', '4× tavan 6.5"', '74 dB', 'Ortam müzik'],
        ['Z2: Ana yemek alanı', '8× tavan 8" + 1 sub', '78 dB', 'Ortam müzik'],
        ['Z3: Bar', '4× tavan + 2× yan-fill', '82 dB', 'Daha yüksek enerji'],
        ['Z4: Teras (varsa)', '4× outdoor IP65', '80 dB', 'Ayrı kaynak'],
      ] },
      { type: 'h2', text: '3. DSP üzerinde adaptif kontrol' },
      { type: 'ul', items: [
        'Saat dilimine göre SPL profili (öğlen +0 dB, akşam +4 dB, gece +6 dB)',
        'Zon başına ayrı EQ - bar zonunda alt-orta vurgu, yemek zonunda 3 kHz cut',
        'Anons mantığı: çağrı butonu basıldığında müzik 12 dB kısılır',
        'Otomatik gürültüye-uyum (ANC) ile kalabalık arttıkça SPL +2 dB',
      ] },
      { type: 'h2', text: '4. Marka bağımsız ürün seçimi' },
      { type: 'p', text: 'Bizim deneyimimizde restoran segmentinde en sık kullanılan markalar Bose Pro (DesignMax), JBL Pro (Control), Tannoy ve Genelec\'tir. Karar mekân hacmine, mimariye ve bütçeye göre değişir.' },
      { type: 'callout', title: 'Sık yapılan hata', text: 'Tavan hoparlöründen kaçınıp duvara büyük subwoofer koymak. Düşük frekans masada konuşmayı boğar; sub sayısı + konumu DSP simülasyonuyla doğrulanmadan kurulmamalı.' },
      { type: 'h2', text: '5. Teslim sonrası ölçüm' },
      { type: 'p', text: 'Devreye alma sonrası en az 6 farklı masa noktasında STI ölçümü zorunludur. STI 0.62 üstü "iyi", 0.75 üstü "mükemmel" anlaşılırlık demektir. Hedef tutturulmadıysa panel revizyonu veya DSP ince ayarı gerekir.' },
    ],
  },
  {
    slug: 'en-54-16-voice-alarm-rehberi',
    title: 'EN 54-16 Voice Alarm: hangi yapılarda zorunlu ve nasıl tasarlanır?',
    summary: 'EN 54-16 sesli tahliye sertifikasının kapsamı, hangi yapılarda yasal olarak zorunlu olduğu ve sistem tasarım adımları.',
    excerpt: 'Sertifikasız anons sistemi sadece hukuki risk değil; can güvenliği riskidir.',
    publishedAt: '2026-05-01',
    readMin: 8,
    category: 'Mevzuat',
    related: { discipline: 'anons' },
    body: [
      { type: 'p', text: 'EN 54-16, Avrupa Standardizasyon Komitesi (CEN) tarafından yayınlanan yangın tahliye seri standardının "Voice Alarm Control and Indicating Equipment" bölümüdür. Türkiye\'de Yangın Yönetmeliği belirli yapı sınıflarında bu sertifikalı sistemi zorunlu kılar.' },
      { type: 'h2', text: 'Hangi yapılarda zorunlu?' },
      { type: 'ul', items: [
        'Alışveriş merkezleri (AVM) - kapasite ve alan eşiği üzerinde',
        'Otel - 50+ oda kapasitesi',
        'Hastane - tüm yataklı tedavi alanları',
        'Okul - orta ve yüksek öğretim binaları',
        'Kamu binası - yapı denetim onayı gereksinimi',
        'Yer altı toplanma alanları (metro istasyonu, otopark, sığınak)',
        'Yüksek katlı binalar (8 kat ve üzeri)',
      ] },
      { type: 'h2', text: 'Sistem bileşenleri' },
      { type: 'p', text: 'EN 54-16 sertifikalı bir sistemin temel parçaları:' },
      { type: 'ul', items: [
        'EN 54-16 sertifikalı kontrol paneli + amfi (Bosch Praesensa, Honeywell INTEVIO, TOA VX)',
        'EN 54-24 sertifikalı hoparlörler (sadece o standardı taşıyan modeller)',
        'EN 54-4 sertifikalı güç kaynağı + 24 saat batarya backup',
        'Yangın paneli ile entegrasyon (Bosch FPA, Honeywell, Siemens Cerberus)',
        'Çağrı mikrofonu + öncelik mantığı (zone bazlı + tüm-bina)',
      ] },
      { type: 'h2', text: 'Tasarım adımları' },
      { type: 'h3', text: '1. Yapının zone planını çıkar' },
      { type: 'p', text: 'Her bağımsız tahliye yolu (kat + blok + kullanıcı tipi kombinasyonu) ayrı bir zone\'dur. Tipik bir 6 katlı otelde: kat başına 2 zone × 6 = 12 + lobi/restoran/SPA/ballroom = 16+ zone.' },
      { type: 'h3', text: '2. Hoparlör yerleşimi ve SPL hedefi' },
      { type: 'p', text: 'Tüm yaşam alanlarında SPL hedefi: arka plan gürültüsünden en az 10 dB yüksek. Tipik ortalama 75 – 95 dB SPL. Hoparlör spacing CEN/TS 54-32 önerilerine göre hesaplanır.' },
      { type: 'h3', text: '3. STI-PA ölçümü' },
      { type: 'p', text: 'Sözel netlik ölçümü EN 54-16 zorunluluğudur. Hedef: STI-PA ≥ 0.50 (her zone için). Ölçüm raporu yapı denetim sürecinde sunulur.' },
      { type: 'callout', title: 'Yaygın hata', text: '"EN 54 uyumlu" değil "EN 54-16 sertifikalı" sistem talep edin. "Uyumlu" terimi pazarlama dili - sertifika belge numarası ihale dosyasında olmalı.' },
      { type: 'h2', text: 'Bakım ve test gereksinimi' },
      { type: 'ul', items: [
        '7 günlük: kontrol paneli görsel + sesli durum kontrolü',
        'Aylık: amfi + batarya yedek testi',
        '6 aylık: STI-PA spot ölçümü en az 2 zone\'da',
        'Yıllık: tüm sistemin sertifikalı yenileme testi + dokümantasyon',
      ] },
      { type: 'p', text: 'Bakım kayıtları yetkili kuruluş tarafından denetlendiğinde tutulur ve genelikle 5 yıl saklama zorunluluğu vardır.' },
    ],
  },
  {
    slug: 'sti-nedir',
    title: 'STI nedir, neden RT60\'tan farklı bir şey ölçer?',
    summary: 'Sözel netliğin tek metriği STI (Speech Transmission Index): tanımı, ölçeği, RT60 ile farkı ve EN 54-16 için zorunlu STI-PA varyantı.',
    excerpt: 'RT60 mekânın akustiğini özetler; STI doğrudan dinleyicinin "sözcüğü ne kadar anladığını" ölçer.',
    publishedAt: '2026-05-01',
    readMin: 6,
    category: 'Akustik',
    related: { discipline: 'akustik' },
    body: [
      { type: 'p', text: 'STI (Speech Transmission Index), bir mekânda konuşulan sözün dinleyiciye ne kadar net ulaştığını sayısal olarak ölçen tek standart metriktir. 0 ile 1 arasında bir değer alır; pratikte 0.45 altı kabul edilemez, 0.62 üstü "iyi", 0.75 üstü "mükemmel" sayılır.' },
      { type: 'h2', text: 'STI değer ölçeği' },
      { type: 'table', caption: 'IEC 60268-16 sözel netlik sınıflaması', headers: ['STI değeri', 'Sözel netlik', 'Tipik kullanım'], rows: [
        ['0.00 – 0.30', 'Bad (kötü)',         'Sözcükler ayırt edilemez'],
        ['0.30 – 0.45', 'Poor (yetersiz)',    'Konuşma çok zorlanarak anlaşılır'],
        ['0.45 – 0.60', 'Fair (vasat)',       'Bağlam yardımıyla anlaşılır - kabul edilemez'],
        ['0.60 – 0.75', 'Good (iyi)',         'Restoran, ofis, sınıf hedefi'],
        ['0.75 – 1.00', 'Excellent (mükemmel)','Stüdyo, broadcast, konferans hedefi'],
      ] },
      { type: 'h2', text: 'STI ile RT60 aynı şey değil' },
      { type: 'p', text: 'Yaygın kafa karışıklığı: "RT60 düşük olsa STI yüksek olur" varsayımı. Doğru ama eksik. STI üç bileşeni hesaba katar:' },
      { type: 'ul', items: [
        '**Yansıma (reverberation)** - RT60\'ın etkisi: yüksek RT60 → STI düşer',
        '**Arka plan gürültüsü (background noise)** - havalandırma, dış gürültü → SNR düşer → STI düşer',
        '**Modülasyon transferi (modulation transfer)** - sistemin frekans + zaman cevabı',
      ] },
      { type: 'p', text: 'Bu yüzden RT60\'ı 0.5 s\'ye indirseniz bile, NC-40 üstü havalandırma gürültüsü STI\'ı 0.55 altına düşürebilir. STI hem akustiği hem ses sistemini hem HVAC mimarisini birlikte denetler.' },
      { type: 'h2', text: 'STI-PA: EN 54-16 için zorunlu varyant' },
      { type: 'p', text: 'EN 54-16 sertifikalı sesli tahliye sistemleri için STI yerine STI-PA (Public Address) varyantı kullanılır. Daha hızlı ölçülebilir ve değerler IEC 60268-16 ile birebir karşılaştırılabilir. EN 54-16 için her zone\'da en az 0.50 STI-PA zorunludur - bunun altı yapı denetim onayını geciktirir.' },
      { type: 'h2', text: 'Saha ölçüm metodolojisi' },
      { type: 'ul', items: [
        'Standart: IEC 60268-16 Edition 5 (2020)',
        'Mikrofon: Sınıf 1 (B&K 4189), pistonphone ile 94 dB SPL kalibre',
        'Sinyal: STI-PA özel test sinyali (modüleli pembe gürültü)',
        'Yazılım: SMAART, ARTA veya ölçüm-spesifik (NTi XL2 + STIPA modülü)',
        'Konum: Mekân hacmine göre 6+ mikrofon noktası, 2 kaynak konumu',
        'Süre: Tek noktada 15 saniye sinyal, ortalama 3 dakika tam ölçüm',
      ] },
      { type: 'callout', title: 'Yaygın hata', text: 'STI ölçümünü tek bir merkezi noktadan yapıp tüm mekâna genellemek. Yansıtıcı duvara yakın masada STI 0.45, sahnenin önündeyse 0.72 olabilir - kabul kriteri "her dinleyici noktası" üzerinden tanımlanır.' },
      { type: 'h2', text: 'Mekân tipine göre STI hedefi' },
      { type: 'table', caption: 'Mekân tipine göre tipik STI hedefi', headers: ['Mekân', 'STI Hedef', 'Not'], rows: [
        ['Restoran',           '≥ 0.62', 'Misafir konuşma netliği için minimum'],
        ['Konferans odası',    '≥ 0.62', 'Hibrit toplantı için kritik'],
        ['Sınıf / amfi',       '≥ 0.65', 'Eğitim alanları için yükseltilmiş hedef'],
        ['Auditorium',         '≥ 0.62', 'Ortalama, en uzak nokta dahil'],
        ['Voice Alarm (VA)',   '≥ 0.50 (STI-PA)', 'EN 54-16 zorunluluğu, her zone'],
      ] },
      { type: 'h2', text: 'STI yetersizse ne yapılır?' },
      { type: 'ul', items: [
        '**RT60 yüksekse:** akustik panel + tavan absorpsiyon ekle',
        '**Arka plan gürültüsü yüksekse:** HVAC sessizlik kontrolü, NC hedefini düşür',
        '**Sistem yetersizse:** beamforming mikrofon, point-source PA yeniden konumlandırma, line array delay ayarı',
        '**Kombinasyon:** çoğu projede üçü birden gerekir - tek başına bir önlem nadiren yeter',
      ] },
      { type: 'p', text: 'Pratikte ölçüm sonrası "RT60 0.7 s ama STI 0.51" gördüğümüzde önce HVAC, sonra hoparlör konumu, en son akustik panele bakarız. Marka veya bütçe değil; metrik karar verir.' },
    ],
  },
  {
    slug: 'line-array-vs-point-source',
    title: 'Line array mı, point source mu? Doğru sistem mimarisi nasıl seçilir?',
    summary: 'İki farklı PA mimarisi arasındaki teknik fark, hangi senaryoda hangisi seçilmeli ve karar matrisi.',
    excerpt: '"Daha büyük her zaman daha iyi" değildir - kötü konfigüre line array, doğru point source\'a yenilir.',
    publishedAt: '2026-05-02',
    readMin: 8,
    category: 'Ses Sistemi',
    related: { discipline: 'ses', venue: 'sahne' },
    body: [
      { type: 'p', text: 'Line array mı point source mu sorusu, ses sistemi tasarımının en sık tartışılan kararıdır. Doğru cevap mekân, izleme mesafesi ve mimari kısıta göre değişir; "her zaman line array" yanıtı pazarlama dilidir, mühendislik değil.' },
      { type: 'h2', text: 'Line array nasıl çalışır?' },
      { type: 'p', text: 'Line array, dikey eksende küçük ve birbirine yakın yerleştirilmiş çoklu hoparlör elemanlarından oluşur. Akustik kaplin (coupling) sayesinde elemanlar tek bir uzun akustik kaynak gibi davranır. Sonuç: dikey eksende dar ve kontrollü ışıma, yatay eksende geniş kapsama.' },
      { type: 'ul', items: [
        '**Avantaj:** uzun mesafede SPL düşüşü daha az (3 dB / mesafe iki katı, point source\'da 6 dB)',
        '**Avantaj:** dikey kontrol - sahne arkasına ve tavan yansımalarına az enerji',
        '**Avantaj:** scale yüksek - 5.000+ kişiyi kapsayabilir',
        '**Dezavantaj:** kurulum karmaşık (rigging, statik hesap, tilt analizi)',
        '**Dezavantaj:** mimari ön hazırlık şart (asma noktaları, yük dağılımı)',
        '**Dezavantaj:** maliyet yüksek',
      ] },
      { type: 'h2', text: 'Point source nasıl çalışır?' },
      { type: 'p', text: 'Point source (nokta kaynak), tek bir hoparlör elemanından oluşan klasik mimarisinin adıdır. Yüksek-Q (dar dispersion) horn yapısıyla belirlenmiş açıyla ışıma yapar. Modern coaxial point source modelleri (Genelec, JBL Control, Bose Pro) küçük-orta mekânlarda son derece etkilidir.' },
      { type: 'ul', items: [
        '**Avantaj:** kurulum basit, hızlı devreye alma',
        '**Avantaj:** maliyet düşük, mimariye az müdahale',
        '**Avantaj:** yakın mesafede mükemmel görüntüleme (imaging)',
        '**Avantaj:** bakım ve değişim kolay',
        '**Dezavantaj:** uzak mesafede SPL düşer (6 dB / 2× mesafe)',
        '**Dezavantaj:** geniş alan için 4+ adet konumlandırma + delay gerekir',
      ] },
      { type: 'h2', text: 'Karar matrisi' },
      { type: 'table', caption: 'Mekân + dinleyici sayısı + dinleme mesafesine göre seçim', headers: ['Senaryo', 'Önerilen Mimari', 'Not'], rows: [
        ['≤ 200 kişi · iç restoran',           'Tavan + 1 sub',                   'Tek zon point source yeter'],
        ['200–800 kişi · ballroom',            'Yüksek-Q point source L/R + sub', 'Çoklu point source delay tower ile birleşir'],
        ['800–2.000 kişi · konser sahnesi',    'Compact line array + cardioid sub', 'Mid-scale line array, 8–12 element'],
        ['2.000–5.000 kişi · büyük sahne',     'Standart line array + delay tower', 'Yatay 90° + dikey 5° kontrol'],
        ['5.000+ kişi · stadyum / festival',   'Large-format line array + delay',   '16+ element + 50 m delay tower'],
        ['Konferans odası / boardroom',        'Tavan beamforming + soft PA',       'Beamforming mic dominant, PA destek'],
      ] },
      { type: 'callout', title: 'Yaygın hata', text: '500 kişilik restoran için "büyük sahne hissi" diye line array öneren satıcılar görüyoruz. Mimariyi bozar, mekâna fazla SPL döker, müşteri konuşamaz hale gelir. Mekân hacmi line array karar kriteri DEĞİLDİR - dinleme mesafesi + mekân kullanımı belirler.' },
      { type: 'h2', text: 'Cardioid sub array - ikisi için de geçerli' },
      { type: 'p', text: 'Hem line array hem point source\'la birlikte kullanabileceğiniz cardioid sub array konfigürasyonu, sahne arkasındaki ses basıncını 12–18 dB azaltır. Performans monitörlüğünü, mikrofon feedback eşiğini ve komşu rezidansa giden bas enerjisini iyileştirir. Modern her teslimde standart önerimizdir.' },
      { type: 'h2', text: 'Simülasyon şart, "kulakla seçim" değil' },
      { type: 'p', text: 'Karar öncesi MAPP (Meyer Sound), Soundvision (L-Acoustics), ArrayCalc (d&b) veya bağımsız EASE simülasyonu yapılır. Mekân CAD\'i, hedef SPL haritası, uniform kapsama varyansı (±2 dB içinde olmalı) çıkarılır. Bu raporu vermeyen sistem entegratöründen şüphelenin.' },
      { type: 'p', text: 'Pratik kural: 3D simülasyon ücretsiz değildir ama yanlış sistem yatırımının %5\'i kadardır. Her büyük projede zorunlu hale getiriyoruz.' },
    ],
  },
  {
    slug: 'led-pixel-pitch-secimi',
    title: 'LED ekranda pixel pitch nasıl seçilir? P1.5 ile P3.9 arasında karar rehberi',
    summary: 'LED ekran kararını belirleyen tek metrik pixel pitch - izleme mesafesine göre P1.5, P2.6, P3.9 nasıl seçilir, processor ve maliyet etkisi.',
    excerpt: 'Çok ince pitch çok güzel görünür ama bütçeyi 3 katına çıkarır. Doğru karar mesafe formülünden başlar.',
    publishedAt: '2026-05-03',
    readMin: 7,
    category: 'LED',
    related: { discipline: 'led' },
    body: [
      { type: 'p', text: 'Pixel pitch, bir LED ekranın iki komşu pikseli arasındaki mesafenin milimetre cinsinden değeridir. P1.5 = 1.5 mm, P2.6 = 2.6 mm vb. Pixel pitch küçüldükçe görüntü detayı artar - ama maliyet ve enerji tüketimi de katlanır. Doğru karar "en ince" değil, "izleme mesafesine uygun en ekonomik" pitch\'tir.' },
      { type: 'h2', text: 'Mesafe formülü (10× kuralı)' },
      { type: 'p', text: 'Sektörel pratik kural: minimum izleme mesafesi (metre) ≈ pixel pitch (mm) × 1.0 ile 1.5 arası. Ortak kullanım için 1.0× yeterli, kritik detay (broadcast, kontrol odası) için 1.5×–2.0× önerilir.' },
      { type: 'table', caption: 'Pixel pitch → izleme mesafesi referans tablosu', headers: ['Pixel Pitch', 'Min. izleme mesafesi', 'Tipik kullanım', 'Yaklaşık piksel/m²'], rows: [
        ['P0.9',  '0.9 – 1.5 m',   'Kontrol odası, broadcast, XR stüdyo',  '≈ 1.235.000'],
        ['P1.2',  '1.2 – 2 m',     'Boardroom, lobi yakın izleme',         '≈ 694.000'],
        ['P1.5',  '1.5 – 3 m',     'Konferans salonu, executive lobi',     '≈ 444.000'],
        ['P1.9',  '1.9 – 3 m',     'Auditorium, hibrit toplantı arkası',   '≈ 277.000'],
        ['P2.6',  '2.6 – 4 m',     'Otel ballroom, etkinlik salonu',        '≈ 148.000'],
        ['P3.9',  '3.9 – 6 m',     'Konser sahnesi (indoor), büyük etkinlik','≈ 65.700'],
        ['P5.9+', '6 – 10 m',      'Outdoor sahne, festival',               '≈ 28.700'],
      ] },
      { type: 'h2', text: 'Maliyet - doğrusal değil eksponansiyeldir' },
      { type: 'p', text: 'P3.9\'dan P2.6\'ya geçiş kabin başına yaklaşık %40 ek maliyet getirir. P1.5\'a geçişte fiyat 3 katına çıkar. Bütçe karar verirken "en iyi olsun" yaklaşımı ciddi cost overrun yaratır.' },
      { type: 'callout', title: 'Pratik tavsiye', text: 'Kapasite > izleme kalitesi olan projelerde önce dinleyici sayısını ve uzaktaki izleme mesafesini belirleyin. P3.9 ile P1.5 arasındaki bütçe farkıyla ek delay tower veya ses sistemi yükseltmesi alabilirsiniz.' },
      { type: 'h2', text: 'Processor seçimi pixel pitch\'ten ayrı bir karar' },
      { type: 'p', text: 'LED panel kadar processor da kritik. Performans hiyerarşisi:' },
      { type: 'ul', items: [
        '**Brompton Tessera SX40 / S8** - touring, XR stüdyo, broadcast premium',
        '**Megapixel HELIOS / OMNIS** - XR stüdyo, frame-accurate genlock',
        '**Novastar MX series** - fixed install ve auditorium dengeli seçim',
        '**Novastar MCTRL series** - bütçe sabit kurulumlar, OEM ile uyumlu',
      ] },
      { type: 'h2', text: 'Refresh rate ve renk yönetimi' },
      { type: 'ul', items: [
        '**Refresh rate ≥ 3.840 Hz** - kamera çekimi olan tüm fixed install için zorunlu (TV broadcast yansıması)',
        '**HDR / Wide gamut** - Brompton Hydra ile kalibre edilebilir; broadcast ve XR stüdyo için kritik',
        '**Color depth ≥ 14 bit** - gradient sahnelerinde band oluşumunu engeller',
        '**Magic Receiver Card** - kabin değişiminde renk tutarlılığı için aynı seri içinde olmalı',
      ] },
      { type: 'h2', text: 'Outdoor için ek kriterler' },
      { type: 'ul', items: [
        '**IP rating** - ön IP65, arka IP54 minimum',
        '**Parlaklık** - 4.000–6.000 nit (gündüz okunabilirlik)',
        '**Kabin ağırlığı** - touring için ≤ 9 kg/kabin',
        '**Service erişim** - front-service zorunlu (truss arkası açılamaz)',
      ] },
      { type: 'h2', text: 'AV-sync - LED tek başına yetmez' },
      { type: 'p', text: 'LED ekran ana PA + lighting + camera ile genlock + frame-lock olmalı. Aksi takdirde frame drift gözle görülür. Tessera processor genlock, Crestron / Q-SYS ile timeline kontrol standart kurulumumuzdur.' },
      { type: 'p', text: 'Karar matrisini paylaşmadan önce her zaman saha keşfi yaparız: izleme mesafesi haritası, ışık koşulu, içerik tipi ve mevcut signal flow. Pixel pitch tek başına ekran kalitesini garanti etmez - ekosistem doğru kurulmalıdır.' },
    ],
  },
  {
    slug: 'dsp-kalibrasyonu-rehberi',
    title: 'DSP kalibrasyonu: devreye almada gerçekte ne yapılır?',
    summary: 'Sistem kurulduktan sonra "ses güzel" diyebilmek için yapılan in-situ DSP tuning sürecinin adım adım rehberi.',
    excerpt: 'Hoparlör kurmak işin %40\'ı; DSP tuning kalan %60. Kalibrasyon olmadan en iyi marka bile kötü sonuç verir.',
    publishedAt: '2026-05-03',
    readMin: 8,
    category: 'Ses Sistemi',
    related: { discipline: 'ses' },
    body: [
      { type: 'p', text: 'DSP kalibrasyonu (system tuning), kurulum sonrası mekânın akustik özelliklerine göre EQ, crossover, delay ve gain yapısının ayarlanmasıdır. Bu adım atlandığında, en pahalı sistem bile ortalama bir sonuç verir. İyi tuning, sıradan bir sistemden mükemmel sonuç çıkarır.' },
      { type: 'h2', text: 'Tuning öncesi hazırlık' },
      { type: 'ul', items: [
        '**HVAC kapatılır** - gürültü tabanı + 5 dB altına inmeli (ölçüm doğruluğu için)',
        '**Mekân boş olmalı** - sahne hazırlığı ve kalabalık akustiği değiştirir, kalibrasyon boş mekânda + sonra dolu mekânda doğrulama yapılır',
        '**Tüm hoparlörler önceki ayarlardan resetlenmelidir** - DSP\'de "factory default", amfi kanal kazançları nötr',
        '**Kalibre mikrofon hazır** - B&K 4189 + pistonphone ile her ölçüm öncesi 94 dB SPL kalibre',
        '**Yazılım bağlantısı** - SMAART v9, REW veya marka-spesifik (Soundvision, Armonia, Q-SYS Designer)',
      ] },
      { type: 'h2', text: '5 aşamalı tuning sırası' },
      { type: 'h3', text: '1. Polarite + faz kontrolü' },
      { type: 'p', text: 'Her hoparlör + sub için polarite doğrulanır. Sub-PA crossover bölgesinde faz uyumu 80 Hz – 200 Hz arasında impulse response ile incelenir. Yanlış polarite tüm ses karakterini bozar - bu adım atlanmaz.' },
      { type: 'h3', text: '2. Crossover ve delay ayarı' },
      { type: 'ul', items: [
        '**Sub-PA crossover** - tipik 80 – 100 Hz, 24 dB/oct LR4 filtre',
        '**Time alignment** - sub ile PA\'nın akustik merkez noktası mesafe farkını delay ile telafi et',
        '**Multi-zone delay** - uzak hoparlörler ana hoparlöre delay ile sync',
        '**Delay tower** - uzak nokta için PA + 30+ ms delay',
      ] },
      { type: 'h3', text: '3. EQ - ölçüm + dinleme' },
      { type: 'p', text: 'EQ yapma stratejisi: önce ölçüm verisi (objective), sonra referans dinleme (subjective). Ölçüm doğru frekans denkliği için, dinleme musical karakter için.' },
      { type: 'ul', items: [
        '**Ölçüm:** smoothing 1/6 oct, hedef X-curve veya Bob Katz K-system referans',
        '**Düzeltme:** notch filtre olarak değil, broad EQ olarak (-3 / +3 dB içinde)',
        '**Doğrulama:** referans müzik (Patricia Barber, Steely Dan, Fink) ile imza kontrolü',
        '**Kayıt:** ölçüm sonrası ve EQ sonrası grafiklerini PDF olarak proje arşivine ekle',
      ] },
      { type: 'h3', text: '4. Gain structure' },
      { type: 'p', text: 'Sinyal zincirinin her bağlantı noktasında (kaynak → DSP → amfi → hoparlör) gain seviyeleri optimize edilir. Tipik hedef: hoparlörün 10 dB peak headroom kalacak şekilde sistem maksimum SPL\'e ulaşmalı.' },
      { type: 'callout', title: 'Sık yapılan hata', text: 'Amfiyi tam açıp DSP\'den kısarak çalışmak. Bu noise floor\'u yükseltir, dinamiği bozar. Doğru: DSP unity gain → amfi kazancı sistem hedefine göre ayarla.' },
      { type: 'h3', text: '5. Limiter + protection' },
      { type: 'p', text: 'Hoparlörün thermal + mekanik limitlerine göre amfi limiter ayarlanır. Modern smart amfiler (Powersoft, Lab.gruppen) hoparlör profilini bilir; manuel limiter ayarı sub-baş için kritik.' },
      { type: 'h2', text: 'Doğrulama metrikleri' },
      { type: 'table', caption: 'Tuning sonrası ölçüm ve hedefler', headers: ['Metrik', 'Hedef', 'Ölçüm Yeri'], rows: [
        ['SPL uniformity (≤ ±2 dB)', 'Tüm dinleyici noktaları için', '6+ mikrofon noktası'],
        ['STI (≥ 0.62)',              'Sözel netlik',                  'Her zone\'da min 3 nokta'],
        ['Phase coherence',           '180° altında crossover bölgesi', 'Sub-PA geçiş'],
        ['Bass response (±3 dB)',     '40 – 80 Hz bandı',              'Sahne önü + arka'],
        ['Delay match',               '< 1 ms tolerans',                'Multi-zone arası'],
      ] },
      { type: 'h2', text: 'Tuning ne kadar sürer?' },
      { type: 'ul', items: [
        '**Restoran (4 zon, point source):** 4 – 6 saat',
        '**Otel ballroom:** 8 – 12 saat',
        '**Konser sahnesi (line array + delay):** 1 – 2 gün',
        '**Konferans odası (beamforming + AEC):** 4 saat + 2 saat hibrit test',
        '**Stüdyo monitör:** 8 saat (Sonarworks veya GLM ile yarı-otomatik)',
      ] },
      { type: 'h2', text: 'Mevsimsel doğrulama' },
      { type: 'p', text: 'İlk tuning yeterli değil - yapı genleşmeleri, mevsimsel nem ve kullanım şartları akustiği değiştirir. Premium SLA müşterilerimizde 6 ayda bir doğrulama ölçümü standarttır. Sapma > ±3 dB ise re-tuning planlanır.' },
    ],
  },
  {
    slug: 'studio-akustigi-rehberi',
    title: 'Stüdyo akustiği: kayan kat, bass trap ve RFZ kontrol odasının fizik temeli',
    summary: 'Mix, tracking ve podcast stüdyolarının akustik temellerinin (modal kontrol, izolasyon, RFZ) tasarım rehberi.',
    excerpt: 'Stüdyoda "iyi monitör" tek başına yeter sanılır; oda kötüyse en iyi monitör bile yalan söyler.',
    publishedAt: '2026-05-04',
    readMin: 9,
    category: 'Stüdyo',
    related: { discipline: 'studio', venue: 'studio' },
    body: [
      { type: 'p', text: 'Stüdyo akustiği, mix ve karar süreçlerinin "doğruluğunu" garanti eden mühendislik katmanıdır. Kontrol odası akustiği bozuksa, mixinizin hangisi gerçek hangisi oda yansıması olduğunu ayırt edemezsiniz. Sonuç: başka bir sistemde dinleyince mix tutarsız çıkar.' },
      { type: 'h2', text: 'Üç temel problem' },
      { type: 'ul', items: [
        '**Modal davranış (modal behavior)** - küçük odalarda 30 – 250 Hz arasında dururlu dalgalar (standing waves) → bas tepkisi pozisyona göre ±15 dB değişir',
        '**Yansıma (early reflections)** - duvardan dinleyiciye gelen ilk yansıma stereo görüntüyü bozar, faz iptali yapar',
        '**İzolasyon eksikliği** - komşu / dış mekân gürültüsü dinamik aralığı sıkar',
      ] },
      { type: 'h2', text: '1. Modal kontrol - bass trap mimarisi' },
      { type: 'p', text: 'Modal pikler, oda boyutlarının yarım dalga boyu katlarıyla rezonansa girmesinden oluşur. Tipik 4×3×2.5 m bir oda 28 Hz, 38 Hz, 57 Hz, 68 Hz, 76 Hz... gibi noktalarda pik yapar. Çözüm: köşelere yerleştirilen geniş bant bass trap kasetleri.' },
      { type: 'ul', items: [
        '**Köşe trap (corner trap)** - 60 cm derinlik, mineral yün dolgu, perforated ön panel',
        '**Membran trap** - belirli frekansları (40 – 80 Hz) tüne edilebilir',
        '**Helmholtz rezonatör** - dar bantta etkili, 60 – 120 Hz hedef',
        '**Süperchunk** - köşeden köşeye uzanan dolgu (en agresif çözüm)',
      ] },
      { type: 'callout', title: 'Pratik kural', text: 'Toplam absorpsiyon hacmi oda hacminin %15-20\'si olmalı (düşük frekans için). Yüzeysel akustik panel modal sorunu çözmez - derinlik şart.' },
      { type: 'h2', text: '2. RFZ - Reflection Free Zone' },
      { type: 'p', text: 'Mix engineer\'ın oturduğu yerde, ön monitörlerden gelen direct sound ile ilk yansıma arasında en az 20 ms zaman farkı (Initial Time Delay Gap) olmalı. Bu "RFZ" zonudur - yansımalar ya absorbe edilir ya da dinleme noktasından uzaklaştırılır.' },
      { type: 'ul', items: [
        '**Yan duvar (mirror point)** - monitör → duvar → dinleme noktası yansımasının tam noktasında geniş bant absorpsiyon',
        '**Ön duvar (monitör arkası)** - broadband absorber + diffüzör kombinasyonu',
        '**Tavan bulutu** - monitör ile dinleyici tepesi arası, açılı asılı panel',
        '**Arka duvar** - diffüzör (Schroeder, QRD) ile yansımayı dağıt, "öldürme"',
      ] },
      { type: 'h2', text: '3. İzolasyon - kayan kat (floating floor)' },
      { type: 'p', text: 'Apartman içindeki stüdyo veya yan komşusu olan kontrol odası için izolasyon kritik. Hedef: −55 dB STC (Sound Transmission Class).' },
      { type: 'h3', text: 'Kayan kat (floating floor) yapısı' },
      { type: 'ul', items: [
        '**Mevcut zemin** - beton (en az 15 cm)',
        '**Neoprene blok** veya **U-boat** isolators - yük dağılımı 40 – 80 kg/m²',
        '**Hava boşluğu** - 5 – 10 cm minimum',
        '**Mineral yün dolgu** - 100 kg/m³ yoğunluk',
        '**Üst plyfloor** - 2× 18 mm OSB veya plywood, kayma direnci için yapışkan değil mekanik bağlantı',
        '**Final yüzey** - vinyl, halı veya laminat',
      ] },
      { type: 'h3', text: 'Duvar - dual-leaf konfigürasyonu' },
      { type: 'ul', items: [
        '**İç katman** - 2× 12.5 mm drywall + 100 mm mineral yün',
        '**Hava boşluğu** - 50 mm ayırma (kritik)',
        '**Dış katman** - 2× 12.5 mm drywall + Green Glue damping katmanı',
        '**Resilient channel** - drywall ile kütle arası mekanik decoupling',
      ] },
      { type: 'h2', text: '4. HVAC - sessiz hava akışı' },
      { type: 'p', text: 'Stüdyo NC-15 / NC-20 hedef, normal HVAC NC-30 / NC-35 üretir. Çözüm: büyük hava kanalı (düşük hız), silencer, lined plenum. Genelde standart HVAC tedarikçisi bunu yapamaz; ses-spesifik akustik mühendisle çalışılır.' },
      { type: 'h2', text: '5. Monitör tuning - son adım' },
      { type: 'p', text: 'Akustik mimari hazırsa, monitör kalibrasyonu son adımdır:' },
      { type: 'ul', items: [
        '**Genelec** - GLM 4 ile otomatik kalibrasyon, oda düzeltmesi monitöre yüklenir',
        '**Neumann KH** - MA 1 mikrofon + Sonarworks SoundID Reference',
        '**Genel** - Sonarworks SoundID, REW + EQ APO (yazılım bazlı)',
        '**Hedef** - referans X-curve veya düz response ±2 dB içinde',
      ] },
      { type: 'h2', text: 'Atmos uyumu - ek konsiderasyon' },
      { type: 'p', text: 'Dolby Atmos sertifikalı stüdyo için ek standartlar var: 9.1.4 / 7.1.4 yerleşim açıları, sub crossover frequency response, surround monitör time alignment Dolby kalibrasyon dokümanına uygun olmalı. Sertifikasyon Dolby tarafından yapılır; biz teknik dokümantasyon ile destekleriz.' },
      { type: 'callout', title: 'Önemli', text: 'Mevcut stüdyoyu retrofit ederken sıralama: önce ölçüm → izolasyon (büyük etki) → modal kontrol → RFZ → monitör tuning. Sıra atlandığında küçük bir etki almak için büyük bütçe harcanır.' },
      { type: 'h2', text: 'Apartmanda stüdyo mümkün mü?' },
      { type: 'p', text: 'Evet - kayan kat + dual-leaf duvar mimarisi ile −55 dB STC sağlanabilir. Ön ölçüm zorunlu. Mimari tarafından "dökme beton katlı" yapı tercih edilir; "delik tuğla" yapılarda izolasyon hedefi daha zor. 5+ kat üst dairelerde sub-bass komşuya geçer; bu yüzden master mix odası genelde alt katlar için tasarlanır.' },
      { type: 'p', text: 'Tipik proje süremiz: 3 m² küçük voice-over kabin için 2 hafta, 25 m² mix kontrol odası için 6 – 8 hafta, 40 m² Atmos sertifika hedefli oda için 10 – 14 hafta.' },
    ],
  },
];

export const getArticle = (slug: string) => ARTICLES.find((a) => a.slug === slug) ?? null;
